// Permission catalog — docs/architecture/04-rbac-permissions.md §4.2.
// This is DATA (seeded into the `permissions` table by packages/db/prisma/seed.ts), not
// role logic. No application code should ever branch on a role name; it should call
// PermissionService.can(user, PERMISSIONS.TASK_ASSIGN, context) instead.

export const PERMISSIONS = {
  ORGANIZATION_CREATE: "organization.create",
  ORGANIZATION_MANAGE: "organization.manage",
  DEPARTMENT_CREATE: "department.create",
  DEPARTMENT_MANAGE: "department.manage",
  TEAM_CREATE: "team.create",
  TEAM_MANAGE: "team.manage",
  TEAM_ASSIGN_HEAD: "team.assign_head",
  TEAM_MANAGE_MEMBERS: "team.manage_members",
  ROLE_MANAGE: "role.manage",
  WORKSPACE_CREATE: "workspace.create",
  PROJECT_CREATE: "project.create",
  PROJECT_MANAGE: "project.manage",
  // Phase 2C — docs/architecture/17-phase2c-project-workspace-architecture-report.md §9.
  // Namespaced `workspace_project.*` (not bare `project.*`) specifically to avoid
  // colliding with PROJECT_CREATE/PROJECT_MANAGE above, which already cover creating/
  // editing the Project row itself and are reused unchanged for that.
  WORKSPACE_PROJECT_MANAGE_MEMBERS: "workspace_project.manage_members",
  WORKSPACE_PROJECT_MANAGE_DATES: "workspace_project.manage_dates",
  TASK_CREATE: "task.create",
  TASK_ASSIGN: "task.assign",
  TASK_ASSIGN_CROSS_TEAM: "task.assign_cross_team",
  TASK_ASSIGN_CROSS_DEPARTMENT: "task.assign_cross_department",
  TASK_ASSIGN_ORG_WIDE: "task.assign_org_wide",
  TASK_ACCEPT: "task.accept",
  TASK_DECLINE: "task.decline",
  TASK_ACCEPT_ON_BEHALF_OF_TEAM: "task.accept_on_behalf_of_team",
  TASK_REASSIGN_INTERNAL: "task.reassign_internal",
  TASK_UPDATE_PROGRESS: "task.update_progress",
  TASK_COMMENT: "task.comment",
  TASK_REVIEW: "task.review",
  TASK_COMPLETE: "task.complete",
  TASK_CANCEL: "task.cancel",
  REPORTS_VIEW: "reports.view",
  AUDIT_VIEW: "audit.view",
  AI_USE: "ai.use",
  AI_CONFIGURE: "ai.configure",
  // Phase 7 — docs/architecture/26-phase7-calendar-meeting-architecture-report.md §13.
  // Deliberately just one permission: creating/organizing your own event. Editing/
  // cancelling/managing participants is ownership-based (organizer-only), not a separate
  // permission grant — mirrors Workday's own "no 'act for someone else' capability" rule
  // (doc 19 §27) rather than TaskAssignment's broader cross-scope permission set, since a
  // calendar event has no assignment/routing concept to authorize.
  CALENDAR_EVENT_CREATE: "calendar_event.create",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_CATALOG: Array<{ key: PermissionKey; description: string }> = [
  { key: PERMISSIONS.ORGANIZATION_CREATE, description: "Create a new organization" },
  { key: PERMISSIONS.ORGANIZATION_MANAGE, description: "Edit org settings, branding, feature flags" },
  { key: PERMISSIONS.DEPARTMENT_CREATE, description: "Create departments" },
  { key: PERMISSIONS.DEPARTMENT_MANAGE, description: "Edit/delete departments" },
  { key: PERMISSIONS.TEAM_CREATE, description: "Create teams" },
  { key: PERMISSIONS.TEAM_MANAGE, description: "Edit/delete teams" },
  { key: PERMISSIONS.TEAM_ASSIGN_HEAD, description: "Designate/remove a Team Head" },
  { key: PERMISSIONS.TEAM_MANAGE_MEMBERS, description: "Add/remove team members" },
  { key: PERMISSIONS.ROLE_MANAGE, description: "Create custom roles, edit role-permission grants" },
  { key: PERMISSIONS.WORKSPACE_CREATE, description: "Create a project workspace" },
  { key: PERMISSIONS.PROJECT_CREATE, description: "Create a project" },
  { key: PERMISSIONS.PROJECT_MANAGE, description: "Edit/delete a project" },
  { key: PERMISSIONS.WORKSPACE_PROJECT_MANAGE_MEMBERS, description: "Add/remove a project's participants (individuals and teams)" },
  { key: PERMISSIONS.WORKSPACE_PROJECT_MANAGE_DATES, description: "Create/edit/delete a project's important dates" },
  { key: PERMISSIONS.TASK_CREATE, description: "Create a task (personal or org)" },
  { key: PERMISSIONS.TASK_ASSIGN, description: "Assign a task within one's own team/scope" },
  { key: PERMISSIONS.TASK_ASSIGN_CROSS_TEAM, description: "Assign a task outside the assignor's own team" },
  { key: PERMISSIONS.TASK_ASSIGN_CROSS_DEPARTMENT, description: "Assign across department boundaries" },
  { key: PERMISSIONS.TASK_ASSIGN_ORG_WIDE, description: "Assign from the organization/management level" },
  { key: PERMISSIONS.TASK_ACCEPT, description: "Accept a task assignment addressed to the user" },
  { key: PERMISSIONS.TASK_DECLINE, description: "Decline a task assignment addressed to the user" },
  { key: PERMISSIONS.TASK_ACCEPT_ON_BEHALF_OF_TEAM, description: "Respond to an assignment addressed to a team" },
  { key: PERMISSIONS.TASK_REASSIGN_INTERNAL, description: "Distribute an accepted team assignment internally" },
  { key: PERMISSIONS.TASK_UPDATE_PROGRESS, description: "Post progress updates on a task" },
  { key: PERMISSIONS.TASK_COMMENT, description: "Comment on a task" },
  { key: PERMISSIONS.TASK_REVIEW, description: "Approve / request changes on a submission" },
  { key: PERMISSIONS.TASK_COMPLETE, description: "Force-complete / close a task" },
  { key: PERMISSIONS.TASK_CANCEL, description: "Cancel a task" },
  { key: PERMISSIONS.REPORTS_VIEW, description: "View team/department/org dashboards & analytics" },
  { key: PERMISSIONS.AUDIT_VIEW, description: "View audit log entries" },
  { key: PERMISSIONS.AI_USE, description: "Use any AI feature (Phase 2+)" },
  { key: PERMISSIONS.AI_CONFIGURE, description: "Toggle/configure AI features for an org (Phase 2+)" },
  { key: PERMISSIONS.CALENDAR_EVENT_CREATE, description: "Create a calendar event (meeting/time commitment)" },
];

// Seeded role templates — docs/architecture/04-rbac-permissions.md §4.3.
export const SYSTEM_ROLE_TEMPLATES: Record<string, PermissionKey[]> = {
  SUPER_ADMIN: PERMISSION_CATALOG.map((p) => p.key),
  ORG_ADMIN: [
    PERMISSIONS.ORGANIZATION_MANAGE,
    PERMISSIONS.DEPARTMENT_CREATE,
    PERMISSIONS.DEPARTMENT_MANAGE,
    PERMISSIONS.TEAM_CREATE,
    PERMISSIONS.TEAM_MANAGE,
    PERMISSIONS.TEAM_ASSIGN_HEAD,
    PERMISSIONS.TEAM_MANAGE_MEMBERS,
    PERMISSIONS.ROLE_MANAGE,
    PERMISSIONS.WORKSPACE_CREATE,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_MANAGE,
    PERMISSIONS.WORKSPACE_PROJECT_MANAGE_MEMBERS,
    PERMISSIONS.WORKSPACE_PROJECT_MANAGE_DATES,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_ASSIGN_CROSS_TEAM,
    PERMISSIONS.TASK_ASSIGN_CROSS_DEPARTMENT,
    PERMISSIONS.TASK_ASSIGN_ORG_WIDE,
    PERMISSIONS.TASK_ACCEPT,
    PERMISSIONS.TASK_DECLINE,
    PERMISSIONS.TASK_ACCEPT_ON_BEHALF_OF_TEAM,
    PERMISSIONS.TASK_REASSIGN_INTERNAL,
    PERMISSIONS.TASK_UPDATE_PROGRESS,
    PERMISSIONS.TASK_COMMENT,
    PERMISSIONS.TASK_REVIEW,
    PERMISSIONS.TASK_COMPLETE,
    PERMISSIONS.TASK_CANCEL,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.AI_CONFIGURE,
    PERMISSIONS.CALENDAR_EVENT_CREATE,
  ],
  DEPARTMENT_HEAD: [
    PERMISSIONS.DEPARTMENT_MANAGE,
    PERMISSIONS.TEAM_CREATE,
    PERMISSIONS.TEAM_MANAGE,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_MANAGE,
    PERMISSIONS.WORKSPACE_PROJECT_MANAGE_MEMBERS,
    PERMISSIONS.WORKSPACE_PROJECT_MANAGE_DATES,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_ASSIGN_CROSS_TEAM,
    PERMISSIONS.TASK_ACCEPT,
    PERMISSIONS.TASK_DECLINE,
    PERMISSIONS.TASK_ACCEPT_ON_BEHALF_OF_TEAM,
    PERMISSIONS.TASK_REASSIGN_INTERNAL,
    PERMISSIONS.TASK_UPDATE_PROGRESS,
    PERMISSIONS.TASK_COMMENT,
    PERMISSIONS.TASK_REVIEW,
    PERMISSIONS.TASK_COMPLETE,
    PERMISSIONS.TASK_CANCEL,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.CALENDAR_EVENT_CREATE,
  ],
  TEAM_HEAD: [
    PERMISSIONS.TEAM_MANAGE_MEMBERS,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_ACCEPT,
    PERMISSIONS.TASK_DECLINE,
    PERMISSIONS.TASK_ACCEPT_ON_BEHALF_OF_TEAM,
    PERMISSIONS.TASK_REASSIGN_INTERNAL,
    PERMISSIONS.TASK_UPDATE_PROGRESS,
    PERMISSIONS.TASK_COMMENT,
    PERMISSIONS.TASK_REVIEW,
    PERMISSIONS.TASK_COMPLETE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.CALENDAR_EVENT_CREATE,
  ],
  MANAGER: [
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_ACCEPT,
    PERMISSIONS.TASK_DECLINE,
    PERMISSIONS.TASK_ACCEPT_ON_BEHALF_OF_TEAM,
    PERMISSIONS.TASK_REASSIGN_INTERNAL,
    PERMISSIONS.TASK_UPDATE_PROGRESS,
    PERMISSIONS.TASK_COMMENT,
    PERMISSIONS.TASK_REVIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.CALENDAR_EVENT_CREATE,
  ],
  MEMBER: [
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_ACCEPT,
    PERMISSIONS.TASK_DECLINE,
    PERMISSIONS.TASK_UPDATE_PROGRESS,
    PERMISSIONS.TASK_COMMENT,
    PERMISSIONS.CALENDAR_EVENT_CREATE,
  ],
};

// Personal workspace has no org scope, so it isn't granted via user_roles — every user
// implicitly has this fixed set of capabilities inside their own personal workspace.
export const INDIVIDUAL_USER_PERMISSIONS: PermissionKey[] = [
  PERMISSIONS.TASK_CREATE,
  PERMISSIONS.TASK_UPDATE_PROGRESS,
  PERMISSIONS.TASK_COMMENT,
  PERMISSIONS.TASK_COMPLETE,
  PERMISSIONS.TASK_CANCEL,
  PERMISSIONS.WORKSPACE_CREATE,
  PERMISSIONS.PROJECT_CREATE,
  PERMISSIONS.PROJECT_MANAGE,
  PERMISSIONS.CALENDAR_EVENT_CREATE,
];
